--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/karuto/.config/wallpaper/clay-banks-u27Rrbs9Dwc-unsplash.jpg"

-- Special
background="#121312"
foreground="#d0cecc"
cursor="#d0cecc"

-- Colors
color0="#121312"
color1="#6D7370"
color2="#7D8079"
color3="#86847B"
color4="#7A8484"
color5="#8F928F"
color6="#A5A19A"
color7="#d0cecc"
color8="#91908e"
color9="#6D7370"
color10="#7D8079"
color11="#86847B"
color12="#7A8484"
color13="#8F928F"
color14="#A5A19A"
color15="#d0cecc"
