# Shell variables
# Generated by 'wal'
wallpaper='/home/karuto/.config/wallpaper/clay-banks-u27Rrbs9Dwc-unsplash.jpg'

# Special
background='#121312'
foreground='#d0cecc'
cursor='#d0cecc'

# Colors
color0='#121312'
color1='#6D7370'
color2='#7D8079'
color3='#86847B'
color4='#7A8484'
color5='#8F928F'
color6='#A5A19A'
color7='#d0cecc'
color8='#91908e'
color9='#6D7370'
color10='#7D8079'
color11='#86847B'
color12='#7A8484'
color13='#8F928F'
color14='#A5A19A'
color15='#d0cecc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
